Feat/quebarbada na midia
quebarbada/landing-page pull request #2
Opened 2022-11-06 17:23 UTC by wesleybridi

Adicionada a section Que Barbada nas versões mobile, tablet e web.

2022-11-07 18:47 UTC, gabriel-moresco commented on src/utils/repository.ts
> +export const news = [
como está muitos repositories em um único arquivo, cria uma pasta "`repositories`" e coloca um arquivo pra cada array. `news.ts`, `supporters.ts`...

2022-11-07 18:50 UTC, gabriel-moresco commented on src/sections/QueBarbadaNaMidiaSection/index.tsx
> +export default function QuebarbadaNaMidia() {
fica muito estranho esse ser um dos unicos componentes escritos em português, sendo que temos uma boa tradução pra isso.

Altera para `InTheMediaSection`

2022-11-07 18:51 UTC, gabriel-moresco commented on src/sections/QueBarbadaNaMidiaSection/index.tsx
> +export default function QuebarbadaNaMidia() {
fica muito estranho esse ser um dos unicos componentes escritos em português, sendo que temos uma boa tradução pra isso.

Altera para `InTheMediaSection`

2022-11-07 18:53 UTC, gabriel-moresco commented on src/styles/slides-que-barbada-na-midia.css
> +#que-barbada-na-midia-section .swiper-button-next,
porque somente esse style em português?

troca pra `slides-in-the-media.css`

2022-11-07 19:02 UTC, gabriel-moresco commented on src/components/SlidesQueBarbadaNaMidia/index.tsx
> +export default function SlidesQueBarbadaNaMidia() {
`SlidesInTheMedia`

2022-11-07 19:08 UTC, gabriel-moresco requested changes
verificar comentários anteriores e fazer as seguintes modificações:

- [x] Utilizar a mesma imagem para as noticias da Engeplus e Noticenter. Vou te passar essa mesma imagem com uma qualidade maior.
- [x] Usar uma imagem de melhor qualidade para a noticia do CanalSC. Vou te passar a nova imagem.
- [ ] Alterar o "card" da noticia para poder selecionar o texto.
- [x] O card inteiro ser um link que redireciona pra notícia
- [x] Retirar o "Saiba mais", pois o link será o card inteiro
- [ ] Embaixo do título da notícia, ter o nome do site da notícia (engeplus, etc...)
- [ ] O border radius do card está fora do padrão com o que ja tem no site (depoimentos)

2022-11-07 19:22 UTC, gabriel-moresco commented
Utilizar a mesma imagem para as noticias da Engeplus e Noticenter. Vou te passar essa mesma imagem com uma qualidade maior

2022-11-11 11:19 UTC, gabriel-moresco commented on src/styles/slides-in-the-media.css
> +#na-midia-section .swiper-button-next,
troca o nome dos estilos pra inglês também

2022-11-11 11:24 UTC, gabriel-moresco commented
ta com erro no build devido a um erro na importação do arquivo `rawCustomers.ts`

![image](https://user-images.githubusercontent.com/45923448/201330704-430c4583-4684-4c8a-9ae2-f8d78a382b08.png)

2022-11-11 11:28 UTC, gabriel-moresco requested changes
verificar comentários anteriores e fazer as seguintes modificações:

- [x] Utilizar a mesma imagem para as noticias da Engeplus e Noticenter.
- [x] Utilizar imagens de alta qualidade dos links abaixo.
- [x] O border radius do card está fora do padrão com o que ja tem no site (depoimentos).
- [ ] retirar a pasta `repositories` de dentro da `utils`, deixar dentro da `src`, e apagar a pasta `utils`.

https://drive.google.com/file/d/10rNiYYKICE535oJDeEoCcwBJW4B9PukD/view?usp=sharing
https://drive.google.com/file/d/10yPlITfBtDtWU3-FudVSgs3svPGT8Aj3/view?usp=sharing

2022-11-11 11:35 UTC, gabriel-moresco commented
link para as imagens em alta qualidade:

https://drive.google.com/file/d/10rNiYYKICE535oJDeEoCcwBJW4B9PukD/view?usp=sharing
https://drive.google.com/file/d/10yPlITfBtDtWU3-FudVSgs3svPGT8Aj3/view?usp=sharing

2022-11-12 12:49 UTC, gabriel-moresco requested changes
- [x] retirar o arredondamento da parte de baixo das imagens (conforme imagem abaixo).
- [x] compactar imagens acima de 2MB.
- [ ] organizar imports dos arquivos.

![image](https://user-images.githubusercontent.com/45923448/201474610-38e75ae8-ad88-49df-ba38-20be6d57a961.png)

2022-11-14 22:47 UTC, wesleybridi commented
Organizei as importações apenas dos arquivos desta section.
Vou criar uma branch para os demais.

2022-11-15 00:15 UTC, gabriel-moresco approved these changes

2022-11-15 00:16 UTC, merged